
# Use this makefile at your own convenience, if you wish.

default: classes

classes: provider protocol

provider:
	cd csec2017; javac *.java

protocol:
	javac *.java

runAlice:
	java Alice

runBob:
	java Bob
